//
// Created by ANTONIO on 30/06/2026.
//

#ifndef P2ELIMINARNODOSHIJOS_ELEMENTOARBOL_H
#define P2ELIMINARNODOSHIJOS_ELEMENTOARBOL_H
struct ElementoArbol {
    int dato;
};
#endif //P2ELIMINARNODOSHIJOS_ELEMENTOARBOL_H
