//
// Created by ANTONIO on 30/04/2026.
//

#ifndef PRACTICAIMPLEMENTACIONLISTA_ELEMENTO_H
#define PRACTICAIMPLEMENTACIONLISTA_ELEMENTO_H

struct Elemento {
  int dni;
};
#endif //PRACTICAIMPLEMENTACIONLISTA_ELEMENTO_H
